-- CRIAÇÃO DA TABELA DE VERSÃO (Low Cost)

-- 1. Cria a tabela
CREATE TABLE IF NOT EXISTS app_versao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    versao_atual TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Insere a versão inicial (V1.0.1)
INSERT INTO app_versao (versao_atual)
VALUES ('1.0.1');

-- 3. Habilita RLS (Row Level Security)
ALTER TABLE app_versao ENABLE ROW LEVEL SECURITY;

-- 4. Cria política de LEITURA PÚBLICA (Necessário para checar antes do login)
-- Permite que qualquer pessoa (anon ou autenticado) leia a versão.
CREATE POLICY "Leitura Pública de Versão"
ON app_versao FOR SELECT
USING (true);

-- 5. Política de Escrita (Apenas Service Role/Admin pode mudar a versão via Dashboard)
-- Não criamos policy de insert/update para 'anon' por segurança.
