-- Create table to store FCM Tokens
create table public.user_fcm_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  fcm_token text not null,
  device_type text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  last_updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (user_id, fcm_token)
);

-- Enable RLS
alter table public.user_fcm_tokens enable row level security;

-- Policies
-- 1. Users can insert their own tokens
create policy "Users can insert their own tokens"
on public.user_fcm_tokens for insert
to authenticated
with check (auth.uid() = user_id);

-- 2. Users can see their own tokens (and Staff can see others?)
-- For simplicity in this MVP to allow client-side sending (personal->student), we allow authenticated read.
-- ideally strictly controlled or via edge function.
create policy "Authenticated users can read tokens"
on public.user_fcm_tokens for select
to authenticated
using (true);

-- 3. Users can delete their own tokens (logout)
create policy "Users can delete their own tokens"
on public.user_fcm_tokens for delete
to authenticated
using (auth.uid() = user_id);

-- 4. Users can update their own tokens (refresh)
create policy "Users can update their own tokens"
on public.user_fcm_tokens for update
to authenticated
using (auth.uid() = user_id);
